### ISSUE TITLE
Chrome Error - Refuse to executle inline event handler

### ISSUE THREAD

**Issue by jlhernando** [ranksense/url-inspector-automator#3]
After I run url_inspector_tool.py and I try to Launch Chrome, it refuses to execute an inline event handler because "it violates the following Content Security Policies". (Image attached)

I've also included my chrome.txt file
[chrome.txt](https://github.com/ranksense/url-inspector-automator/files/3272530/chrome.txt)
![aj3SIIHM](https://user-images.githubusercontent.com/14793651/59204309-44f97600-8b98-11e9-8e68-7264a22cb379.png)
![wJHVeTjn](https://user-images.githubusercontent.com/14793651/59204310-45920c80-8b98-11e9-9f17-050cd5957ae2.png)

**Comment by hamletbatista** [comment]
@jlhernando this seems like an issue with Chrome. Can you try exiting Chrome (all windows) and trying again?

> [2956:19008:0610/132120.465:ERROR:cache_util_win.cc(21)] Unable to move the cache: Access is denied. (0x5)
> [2956:19008:0610/132120.465:ERROR:cache_util.cc(141)] Unable to move cache folder C:\Users\Jose\Documents\url-inspector-automator\chrome-dev\ShaderCache\GPUCache to C:\Users\Jose\Documents\url-inspector-automator\chrome-dev\ShaderCache\old_GPUCache_000
> [2956:19008:0610/132120.465:ERROR:disk_cache.cc(178)] Unable to create cache
> [2956:19008:0610/132120.465:ERROR:shader_disk_cache.cc(623)] Shader Cache Creation failed: -2
> [1424:5856:0610/132121.384:ERROR:CONSOLE(1)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-r1drsgoDPQZulnXwabgollhGK3T7e1MR/3dT/kdnsHk=' 'sha256-7Ev0+xudUJf+TNOaD7bOGEsbqNx10CoivlMga0NvMM8=' 'sha256-JJcFw5vJcK0RjK1BZMPVDPOXUXIxZOVOdS1UlR8I0oc=' 'sha256-455z/8g1DIg5Sdxz0lA1l+6+NbtUDQL5F6wsSWq4awg=' 'sha256-98oC9MOukj1vqRurBgSvb3ckqChyJKNnthWgATTmugg=' 'sha256-QtaEGY7z+CISGaCsQAzXgfpAMMmdekW9iw+F6VckWbs=' 'sha256-oYWge86q8v6E3ho4y79Dz2BQ4DXghaz5vCPJlx2KqlM='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
> ", source: chrome-search://local-ntp/local-ntp.html (1)
> [1424:5856:0610/132141.886:ERROR:CONSOLE(4451)] "No document", source: devtools://devtools/bundled/shell.js (4451)
> [1424:10964:0610/133642.005:ERROR:socket_stream.cc(219)] Closing stream with result -2

**Comment by jlhernando** [comment]
Hi @hamletbatista Thanks very much. It was that. Now it's working perfectly :) Many thanks!
